name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build for Linux
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -o llm-input-tuku-ru_linux_amd64 main.go
    
    - name: Build for Mac OS
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -o llm-input-tuku-ru_darwin_amd64 main.go

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: | 
          llm-input-tuku-ru_linux_amd64
          llm-input-tuku-ru_darwin_amd64
